repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|svelte)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-prettier@8.5.0
          - eslint-plugin-svelte@2.30.0
          - prettier-plugin-svelte@2.10.1

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, svelte, json, css, html]
        additional_dependencies:
          - prettier@2.8.0
          - prettier-plugin-svelte@2.10.1

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v15.11.0
    hooks:
      - id: stylelint
        files: \.(css|scss|sass)$
        args: [--fix]
        additional_dependencies:
          - stylelint@15.11.0
          - stylelint-config-standard@34.0.0
